### ISSUE TITLE
can you add  vesti.ru :) ?

### ISSUE THREAD

**Issue by 1o1o1** [zhovner/zaborona_help#188]
can you add  vesti.ru :)  https://hitech.vesti.ru/

Thank you

**Comment by toxi22** [comment]
Hello!
For the site https://hitech.vesti.ru/ to work correctly, you need to change the port for connecting from 1194 to 1196, in the OpenVPN settings :)

**Comment by 1o1o1** [comment]
Yes! it's working)  why? can you explain this?

**Comment by toxi22** [comment]
It is perfectly! :)

The sites are divided into two categories.
1. If you only need social networks and nothing else, use port 1194
2. If you need social networks, WebMoney and access to other sites blocked sites, use port 1196.

This had to be done because the error was appearing:
"OpenVPN ROUTE: cannot add more than 100 routes. Please increase the max routes option in the client configuration file" and because of this, new sites could not be added to the bypass block list.
